#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanCase0

rm liquidHeight_average.png  liquidHeight_xCenter.png  liquidHeight_xComparison.png  x0.5z0.5_p_p_rgh.png  ./0/alpha.water

#------------------------------------------------------------------------------
