#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp ../capillaryRise/0/alpha.water.orig 0/alpha.water
restore0Dir
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $application
runApplication reconstructPar
runApplication -s sample postProcess -func sample

runApplication ./scripts/createGraphs

#------------------------------------------------------------------------------
